---
# tasks file for egeneralov.lxc

- name: install lxc
  apt:
    name: lxc
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: lxc networking configuration
  lineinfile:
    path: /etc/default/lxc-net
    create: yes
    line: "{{ item.l }}"
    regexp: "{{ item.r }}"
  with_items: "{{ lxc.net }}"
  register: lxc_net_conf

- name: (re)start lxc-net
  systemd:
    name: lxc-net
    state: "{% if lxc_net_conf is changed %}re{% endif %}started"
    enabled: yes

- name: lxc default container configuration
  lineinfile:
    path: /etc/lxc/default.conf
    line: "{{ item.l }}"
    regexp: "{{ item.r }}"
  with_items: "{{ lxc.conf }}"
  register: lxc_conf

- name: (re)start lxc
  systemd:
    name: lxc
    state: "{% if lxc_conf is changed %}re{% endif %}started"
    enabled: yes
